local_planner:
  plugin: "dwb_core::DWBLocalPlanner"
  debug_trajectory_details: true

  # DWA parameters
  dwb:
    min_vel_x: 0.0
    max_vel_x: 0.5
    min_vel_y: 0.0
    max_vel_y: 0.0  # For differential drive robots
    min_speed_theta: 0.0
    max_speed_theta: 1.0
    acc_lim_x: 0.5
    acc_lim_y: 0.0
    acc_lim_theta: 1.0
    decel_lim_x: -0.5
    decel_lim_y: 0.0
    decel_lim_theta: -1.0

    # Critic types for scoring trajectories
    critic_types:
      - "RotateToGoal"
      - "Oscillation"
      - "ObstacleFootprint"
      - "GoalAlign"
      - "PathAlign"

    # Weights for trajectory scoring
    goal_distance_weight: 1.0
    path_distance_weight: 1.0
    obstacle_cost_weight: 10.0
